# analog_video_protection_level
ANALOG_VIDEO_PROTECTION_LEVEL = (100, 150, 200, 201)

LEVEL_100 = ANALOG_VIDEO_PROTECTION_LEVEL[0]  # 'LEVEL_100'
LEVEL_150 = ANALOG_VIDEO_PROTECTION_LEVEL[1]  # 'LEVEL_150'
LEVEL_200 = ANALOG_VIDEO_PROTECTION_LEVEL[2]  # 'LEVEL_200'
LEVEL_201 = ANALOG_VIDEO_PROTECTION_LEVEL[3]  # 'LEVEL_201'

def check(analog_video_protection) -> bool:
    return analog_video_protection in ANALOG_VIDEO_PROTECTION_LEVEL
