# required_hdcp_version
REQUIRED_HDCP_VERSION = ('HDCP_NONE', 'HDCP_V1', 'HDCP_V2', 'HDCP_V2_1', 'HDCP_V2_2', 'HDCP_NO_DIGITAL_OUTPUT')

HDCP_NONE = REQUIRED_HDCP_VERSION[0]
HDCP_V1 = REQUIRED_HDCP_VERSION[1]
HDCP_V2 = REQUIRED_HDCP_VERSION[2]
HDCP_V2_1 = REQUIRED_HDCP_VERSION[3]
HDCP_V2_2 = REQUIRED_HDCP_VERSION[4]
HDCP_NO_DIGITAL_OUTPUT = REQUIRED_HDCP_VERSION[5]

def check(hdcp_version) -> bool:
    return hdcp_version in REQUIRED_HDCP_VERSION
