REQUIRED_CGMS_FLAGS = ('CGMS_NONE', 'COPY_FREE', 'COPY_ONCE', 'COPY_NEVER')

CGMS_NONE = REQUIRED_CGMS_FLAGS[0]
COPY_FREE = REQUIRED_CGMS_FLAGS[1]
COPY_ONCE = REQUIRED_CGMS_FLAGS[2]
COPY_NEVER = REQUIRED_CGMS_FLAGS[3]

def check(cgms_flags) -> bool:
    return cgms_flags in REQUIRED_CGMS_FLAGS
