SECURITY_LEVEL = (1, 2, 3, 4, 5)

SW_SECURE_CRYPTO = SECURITY_LEVEL[0]  # 'SW_SECURE_CRYPTO'
SW_SECURE_DECODE = SECURITY_LEVEL[1]  # 'SW_SECURE_DECODE'
HW_SECURE_CRYPTO = SECURITY_LEVEL[2]  # 'HW_SECURE_CRYPTO'
HW_SECURE_DECODE = SECURITY_LEVEL[3]  # 'HW_SECURE_DECODE'
HW_SECURE_ALL = SECURITY_LEVEL[4]  # 'HW_SECURE_ALL'

def check(security_level) -> bool:
    return security_level in SECURITY_LEVEL
